# Generated by Django 5.0.1 on 2024-01-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boto3app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
